from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from app.domain.assets import CreatorAssetRecord
from app.domain.course import CourseEvent, CourseRun, CourseRunSummary
from app.domain.learner import (
    LearnerEnrollment,
    LearnerEnrollmentSummary,
    LearnerSubmissionRecord,
    LearnerWorkspaceSession,
)
from app.domain.publish import PublishSnapshot, PublishSnapshotSummary
from app.domain.testing import (
    CreatorFeedbackRecord,
    LearnerCourseEvaluationReport,
    LearnerFeedbackRecord,
)
from app.domain.workflow import WorkflowEvent, WorkflowRun, WorkflowRunSummary


@runtime_checkable
class WorkflowStore(Protocol):
    def utcnow(self) -> datetime: ...

    def save_run(self, run: WorkflowRun) -> WorkflowRun: ...
    def get_run(self, run_id: str) -> WorkflowRun | None: ...
    def list_runs(self, limit: int = 50) -> list[WorkflowRunSummary]: ...

    def append_event(self, run_id: str, event_type: str, payload: dict) -> WorkflowEvent: ...
    def list_events(self, run_id: str) -> list[WorkflowEvent]: ...

    def save_course_run(self, run: CourseRun) -> CourseRun: ...
    def get_course_run(self, course_run_id: str) -> CourseRun | None: ...
    def list_course_runs(self, limit: int = 50) -> list[CourseRunSummary]: ...

    def append_course_event(self, course_run_id: str, event_type: str, payload: dict) -> CourseEvent: ...
    def list_course_events(self, course_run_id: str) -> list[CourseEvent]: ...

    def reset_all(self) -> dict[str, int]: ...

    def save_creator_asset(self, asset: CreatorAssetRecord) -> CreatorAssetRecord: ...
    def get_creator_asset(self, asset_id: str) -> CreatorAssetRecord | None: ...
    def list_creator_assets(self, limit: int = 100) -> list[CreatorAssetRecord]: ...
    def delete_creator_asset(self, asset_id: str) -> bool: ...

    def save_learner_enrollment(self, enrollment: LearnerEnrollment) -> LearnerEnrollment: ...
    def get_learner_enrollment(self, enrollment_id: str) -> LearnerEnrollment | None: ...
    def find_learner_enrollment(self, learner_id: str, course_run_id: str) -> LearnerEnrollment | None: ...
    def list_learner_enrollments(
        self, learner_id: str | None = None, limit: int = 50
    ) -> list[LearnerEnrollmentSummary]: ...

    def save_learner_submission(self, submission: LearnerSubmissionRecord) -> LearnerSubmissionRecord: ...
    def list_learner_submissions(
        self, enrollment_id: str, deliverable_id: str | None = None
    ) -> list[LearnerSubmissionRecord]: ...

    def save_learner_workspace_session(self, session: LearnerWorkspaceSession) -> LearnerWorkspaceSession: ...
    def list_learner_workspace_sessions(self, enrollment_id: str) -> list[LearnerWorkspaceSession]: ...
    def list_all_learner_workspace_sessions(self) -> list[LearnerWorkspaceSession]: ...

    def save_publish_snapshot(self, snapshot: PublishSnapshot) -> PublishSnapshot: ...
    def get_publish_snapshot(self, snapshot_id: str) -> PublishSnapshot | None: ...
    def list_publish_snapshots(
        self,
        course_run_id: str | None = None,
        course_family_id: str | None = None,
        limit: int = 50,
    ) -> list[PublishSnapshotSummary]: ...
    def get_latest_publish_snapshot(
        self,
        course_run_id: str | None = None,
        course_family_id: str | None = None,
    ) -> PublishSnapshot | None: ...

    def save_creator_feedback(self, feedback: CreatorFeedbackRecord) -> CreatorFeedbackRecord: ...
    def list_creator_feedback(self, course_run_id: str, limit: int = 100) -> list[CreatorFeedbackRecord]: ...

    def save_learner_feedback(self, feedback: LearnerFeedbackRecord) -> LearnerFeedbackRecord: ...
    def list_learner_feedback(self, enrollment_id: str, limit: int = 100) -> list[LearnerFeedbackRecord]: ...

    def save_learner_eval_report(
        self, report: LearnerCourseEvaluationReport
    ) -> LearnerCourseEvaluationReport: ...
    def list_learner_eval_reports(
        self,
        course_run_id: str | None = None,
        publish_snapshot_id: str | None = None,
        limit: int = 100,
    ) -> list[LearnerCourseEvaluationReport]: ...
    def get_latest_learner_eval_report(
        self,
        course_run_id: str,
        publish_snapshot_id: str | None = None,
    ) -> LearnerCourseEvaluationReport | None: ...

    # auth surface
    def create_user(self, *, email: str, password_hash: str, role, display_name: str | None = None): ...
    def get_user_by_email(self, email: str): ...
    def get_user_password_hash(self, email: str) -> str | None: ...
    def get_user_by_id(self, user_id): ...
    def create_user_session(self, *, user_id, expires_at, ip, user_agent): ...
    def load_user_session(self, session_id): ...
    def revoke_user_session(self, session_id) -> None: ...
